### ISSUE TITLE
Open menu via command

### ISSUE THREAD

**Issue by oethanx** [eyal282/Ban-Disconnected#1]
A command to open up the disconnected players menu would be a nice addition to the plugin.

**Comment by eyal282** [comment]
> A command to open up the disconnected players menu would be a nice addition to the plugin.

Added, does it work?

sm_commdisconnected and sm_bandisconnected now open each of their menu.

sm_bandisconnected used to add ban by steam ID as a chat command, but every self respecting ban system has !addban. If not, get Sourcebans++ or my SQLite Bans plugin:

https://forums.alliedmods.net/showthread.php?t=315623
